#!/usr/bin/env node
// Copy the shared sheets into the repositories that cannot import them.
//
// Task jwildfire/obot.agent#295.
//
//   node obot.agent/tools/style/vendor.mjs           # write the vendored copies
//   node obot.agent/tools/style/vendor.mjs --check   # report drift, write nothing
//   node obot.agent/tools/style/vendor.mjs --dest obot.roadmap:/path/to/worktree
//
// `--dest` points one repository at a checkout other than the sibling clone. Vendoring
// happens while the adopting change is on a branch, and a branch lives in a linked
// worktree here — without this the script would write the new bytes into the clone
// sitting on main, where the pull request cannot see them and nobody asked for them.
//
// ## Why a copy exists at all, when the whole point was to stop copying
//
// obot.roadmap's deploy workflow checks out obot.roadmap and gh.dash and nothing
// else, so a hub generator cannot import obot.agent/assets/obot-css.mjs at deploy
// time — the file is not on the runner. Importing the hub's code from here is
// separately unsafe: its local-only-guard patches node:fs process-wide on import
// (obot.agent#206), so anything that named-imports its way in goes blind and starts
// reporting present files as absent.
//
// That leaves vendoring. The distinction that matters is not copy versus no copy —
// it is whether anything is looking. A vendored file carries a provenance header
// naming the commit it came from, and tools/style/census.mjs compares its bytes to
// the canonical ones on every run. A copy that cannot drift without going red is a
// different thing from a copy nobody checks, and this program has been bitten
// repeatedly by the second kind.
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

import { VENDORED } from './surfaces.mjs';
import { workspaceRoot, REPO } from './census.mjs';

const argv = process.argv.slice(2);
const check = argv.includes('--check');

/** repo name -> checkout, for a destination that is not the sibling clone. */
const dest = new Map();
for (let i = 0; i < argv.length; i++) {
  if (argv[i] !== '--dest') continue;
  const [name, at] = String(argv[i + 1] ?? '').split(':');
  if (!name || !at) { console.error('vendor: --dest wants <repo>:<path>'); process.exit(1); }
  if (!fs.existsSync(at)) { console.error(`vendor: --dest ${name}: no such checkout: ${at}`); process.exit(1); }
  dest.set(name, path.resolve(at));
}

const root = workspaceRoot();
if (!root && !dest.size) { console.error('vendor: no workspace root above this repo, and no --dest given'); process.exit(1); }

/** Where a workspace-relative path is written, honouring --dest. */
function at(rel) {
  const [repo, ...rest] = rel.split('/');
  if (dest.has(repo)) return path.join(dest.get(repo), ...rest);
  if (repo === 'obot.agent') return path.join(REPO, ...rest);
  return root ? path.join(root, rel) : null;
}

/** The commit the canonical sheet is at, so a reader can find the source of these bytes. */
function sourceCommit() {
  try {
    return execFileSync('git', ['-C', REPO, 'rev-parse', '--short', 'HEAD'], { encoding: 'utf8' }).trim();
  } catch { return 'unknown'; }
}

const commit = sourceCommit();
let drift = 0;

for (const v of VENDORED) {
  const src = at(v.from);
  const dst = at(v.to);
  if (!dst) { console.error(`vendor: ${v.to} — that repository is not on this machine`); continue; }
  if (!fs.existsSync(src)) { console.error(`vendor: canonical sheet missing: ${v.from}`); process.exit(1); }

  const canonical = fs.readFileSync(src, 'utf8');
  // The header names where the bytes came from and forbids editing here. The census
  // strips exactly this header before comparing, so stamping is never read as drift.
  const header = `/* VENDORED — do not edit this file.\n`
    + ` * Copied from ${v.from} at obot.agent ${commit} by obot.agent/tools/style/vendor.mjs.\n`
    + ` * ${v.why}\n`
    + ` * Edit the canonical sheet and re-run the vendor script; the census goes red on drift. */\n`;
  const wanted = header + canonical;

  const current = fs.existsSync(dst) ? fs.readFileSync(dst, 'utf8') : null;
  const same = current !== null && current.replace(/^\/\* VENDORED[\s\S]*?\*\/\n/, '') === canonical;

  if (check) {
    if (!same) { drift++; console.log(`DRIFT  ${v.to}  ${current === null ? 'missing' : 'differs from ' + v.from}`); }
    else console.log(`ok     ${v.to}`);
    continue;
  }

  if (same) { console.log(`unchanged  ${v.to}`); continue; }
  fs.mkdirSync(path.dirname(dst), { recursive: true });
  fs.writeFileSync(dst, wanted);
  console.log(`wrote      ${v.to}  (from ${v.from} at ${commit})`);
}

if (check && drift) process.exit(1);
